### ISSUE TITLE
GB Donations Multiplier Resets to 0.03

### ISSUE THREAD

**Issue by sausage-eater** [FoE-Info/FoE-Info-Extension#8]
GB Donations Arc multiplier gets intermittently reset to 0.03 (from the default 1.9 or higher). This started happening after an upgrade to version 0.0.80 of the plugin. I just flipped my GB because of that and lost double-dip.

![image](https://user-images.githubusercontent.com/117865142/223724476-4bee7a14-6731-4683-a997-439b1a4bc963.png)

**Comment by kronikpillow** [comment]
thanks for the report, we are aware of the issue, this is happening because we changed the GB Donation Panel to recognize thread titles and adjust ratio based on Thread Title, so if thread contains 1.90-2.00 or 190% up to 200% in thread title, it will auto adjust to that % ... 

The above bug happens sometimes when you open your GB from your GB list, without using a thread ... which strangely doesn't happen every time, while when it does happen, it's not using the setting that is set in the Settings page ... 

weird, we are investigating :)

**Comment by kronikpillow** [comment]
we also had reports of something like this, using a 5.39 setting 🤣🤣

![image](https://user-images.githubusercontent.com/48420193/224020194-2cc48d41-ff9d-46e1-93ab-c6ce28fa0084.png)

**Comment by kronikpillow** [comment]
this should be solved with v0.81 release coming tonight ... please report back if issue persists
